### ISSUE TITLE
Deleting Requirements Broken

### ISSUE THREAD

**Issue by NateTHEgreatest33** [sevendays/doorhole#11]
LIne 380 an older style of QMessageBox() return that is no longer supported in PyQt6 (see this [discussion](https://stackoverflow.com/questions/65735260/alternative-to-qmessagebox-yes-for-pyqt6))

Should be changed from:
`if ret == qm.Yes:`
to:
`if ret == QMessageBox.StandardButtons.Yes.value:`

**Comment by sevendays** [comment]
Hey there @NateTHEgreatest33 , thanks for the heads up!

Did you spot other areas where updating to PyQt6 could be a problem?
Could you do a PR?

**Comment by NateTHEgreatest33** [comment]
sounds good, ill create a PR!
I haven't spent too much time with doorhole yet but I plan to in the coming week so if I see anything else I'll create new PR's

**Comment by sevendays** [comment]
Thanks! I took the chance to define a review rule to force myself out of laziness and actually examine the changes
