### ISSUE TITLE
An error occurred while displaying the content : module 'markdown' has no attribute 'version_info'

### ISSUE THREAD

**Issue by DaPa** [sevendays/doorhole#2]
Thank you for this nice script!
I tried your latest script over the doorstop's repo and getting this "An error occurred while displaying the content : module 'markdown' has no attribute 'version_info'" in every cell. Can you please confirm and if yes do you know the reason?

![image](https://user-images.githubusercontent.com/4947697/104481535-923c9580-55ce-11eb-841f-d08003f7c889.png)

Environment: Windows 10 1909.x64 with Python 3.9.1 and Doorstop v2.1.2. Also had to install PySide (Successfully installed PySide2-5.15.2 shiboken2-5.15.2) and Markdown was already fine (Requirement already satisfied: markdown in d:\tools\python\39\lib\site-packages (2.6.11)).

```
D:\work\mine\doorstop_test\doorstop>python --version
Python 3.9.1

D:\work\mine\doorstop_test\doorstop>doorstop --version
Doorstop v2.1.2

D:\work\mine\doorstop_test\doorstop>doorstop
building tree...
loading documents...
validating items...
WARNING: TUT: TUT003: no text
WARNING: TUT: TUT003: no links to parent document: REQ
WARNING: TUT: TUT003: no links from child document: HLT
REQ
│
├── LLT
│
└── TUT
    │
    └── HLT

D:\work\mine\doorstop_test\doorstop>doorhole
DEBUG:__main__:[REQ] Custom requirements attributes: set()
DEBUG:__main__:[REQ] Requirements reloaded
DEBUG:__main__:[LLT] Custom requirements attributes: set()
DEBUG:__main__:[LLT] Requirements reloaded
DEBUG:__main__:[TUT] Custom requirements attributes: set()
DEBUG:__main__:[TUT] Requirements reloaded
DEBUG:__main__:[HLT] Custom requirements attributes: set()
DEBUG:__main__:[HLT] Requirements reloaded
```

**Comment by DaPa** [comment]
I tried to _force_ upgrade markdown to latest (3.3.3) which succeeded (after a strange warning):
```
D:\work\mine\doorstop_test\doorstop>pip install markdown --upgrade
Requirement already satisfied: markdown in d:\tools\python\39\lib\site-packages (2.6.11)
Collecting markdown
  Downloading Markdown-3.3.3-py3-none-any.whl (96 kB)
     |████████████████████████████████| 96 kB 2.2 MB/s
Installing collected packages: markdown
  Attempting uninstall: markdown
    Found existing installation: Markdown 2.6.11
    Uninstalling Markdown-2.6.11:
      Successfully uninstalled Markdown-2.6.11
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
doorstop 2.1.2 requires Markdown<3.0,>=2.0, but you have markdown 3.3.3 which is incompatible.
Successfully installed markdown-3.3.3
```

and now the error changed a bit.
"An error occurred while displaying the content : 'xml.etree.ElementTree.Element' object has no attribute 'getchildren'":

![image](https://user-images.githubusercontent.com/4947697/104488037-81901d80-55d6-11eb-9356-f589a3febb43.png)

**Comment by sevendays** [comment]
Hi @DaPa , thanks for trying it out!

Right now I'm using win10 x64, python 3.8.3, Markdown 2.6.11:

![immagine](https://user-images.githubusercontent.com/301673/104508496-98d80680-55e8-11eb-836c-c2b58ab37944.png)

I remember I had a problem like the one you're experiencing.
Your error may be related to the **PlantUML Markdown extension** not working properly due to firewalls blocking plantuml.com. I had to install plantUML locally (requires java), setup a batch script and put it in $path, and clear out the "server" parameter in the extensions configuration (see below).

TUT017 has an UML state machine, if it doesn't work then the error is definitely related to plantUML not being present locally on your system:

![immagine](https://user-images.githubusercontent.com/301673/104509653-413a9a80-55ea-11eb-8a25-7f6ffb282bd6.png)


Could you please try changing this snippet (lines 19-32) from:

```
EXTENSIONS = (
	'markdown.extensions.extra',
	'markdown.extensions.sane_lists',
	'mdx_outline',
	'mdx_math',
	PlantUMLMarkdownExtension(
		server='',#'http://www.plantuml.com/plantuml',
		cachedir=tempfile.gettempdir(),
		format='svg',
		classes='class1,class2',
		title='UML',
		alt='UML Diagram',
	),
)
```
to:

```
EXTENSIONS = (
	'markdown.extensions.extra',
	'markdown.extensions.sane_lists',
	'mdx_outline',
	'mdx_math',
	PlantUMLMarkdownExtension(
		server='http://www.plantuml.com/plantuml',
		cachedir=tempfile.gettempdir(),
		format='svg',
		classes='class1,class2',
		title='UML',
		alt='UML Diagram',
	),
)
```

and let me know?

**Comment by DaPa** [comment]
Thank you for your fast answer! Indeed for me the PlantUML is not rendered with the original script (empty server and local PlantUml+Graphviz install) nor with the changed one (online server). Here's the online change how you suggested:
![image](https://user-images.githubusercontent.com/4947697/104517612-01ca7900-55ff-11eb-9b32-d2d25a2660d8.png)

In both situations I have the same "raw" output:
![image](https://user-images.githubusercontent.com/4947697/104517198-443f8600-55fe-11eb-9f64-a133caaa0db5.png)

I did checked that the local PlantUml+Graphviz setup should work follow these steps:
- I have dot.exe into D:\tools\Graphviz\bin\
- then plantuml.jar into D:\tools\plantUml\
- boths paths are added to Environment Variables:
![image](https://user-images.githubusercontent.com/4947697/104518273-27a44d80-5600-11eb-9749-bfeec78164dd.png)

- then plantuml.bat is in the same D:\tools\plantUml\ with following content:
```
@echo off
set mypath=%~dp0
setlocal
set GRAPHVIZ_DOT=%mypath%..\Graphviz\bin\dot.exe
java %PLANTUML_JAVAOPTS% -jar %mypath%\plantuml.jar %*
```
The test was as follows:
- in totally unrelated folder I have two files 1.txt and 2.md with following contents:
```
@startuml
[*] -> State1
State1 --> State2 : Succeeded
State1 --> [*] : Aborted
State2 --> State3 : Succeeded
State2 --> [*] : Aborted
state State3 {
  state "Accumulate Enough Data\nLong State Name" as long1
  long1 : Just a test
  [*] --> long1
  long1 --> long1 : New Data
  long1 --> ProcessData : Enough Data
}
State3 --> State3 : Failed
State3 --> [*] : Succeeded / Save Result
State3 --> [*] : Aborted
@enduml
```

```
# some md file with diagram
```plantuml
@startuml
Actor1 -> Actor2: "Info exchanged"
@enduml
```#
```

- opened command prompt to that folder and issued plantuml for both files:
![image](https://user-images.githubusercontent.com/4947697/104518886-26275500-5601-11eb-9c02-779866dadd10.png)
- 1.png and 2.png were created correctly as below:
![image](https://user-images.githubusercontent.com/4947697/104518982-566ef380-5601-11eb-8b6a-0debca8e6bd8.png)
![image](https://user-images.githubusercontent.com/4947697/104519009-6090f200-5601-11eb-99b0-f273169b8089.png)

Also for the online situation I can access http://www.plantuml.com/plantuml from any browser without issue:
![image](https://user-images.githubusercontent.com/4947697/104519379-017fad00-5602-11eb-89f1-13362f8e0a04.png)

So I don't know yet why the uml are not generated and also what's the reason of 'version_info' markdown error.
Next step would be to try downgrading to python 3.8.3 as you have. I'll try to come tomorrow with update on this.

**Comment by DaPa** [comment]
Downgrading to python 3.8.3 didn't help. I then removed the the PlantUml requirement from the Doorstop repo and it didn't help.
I then created a new empty repo with 3 small requirements and still getting the _module 'markdown' has no attribute 'version_info'_ error.
![image](https://user-images.githubusercontent.com/4947697/104558657-d326bf80-564b-11eb-88ea-5f4575870b3e.png)
The only place I found similar issue is https://github.com/saltstack/salt/issues/32261
I'll continue digging...

**Comment by DaPa** [comment]
Small update: for debugging I made one single requirement which is SRD002.yml with this content:
```
active: true
derived: false
header: ''
level: 2
links: []
normative: true
ref: ''
reviewed: null
text: |
  Some dummy text
```
and which for me is rendered like this:
![image](https://user-images.githubusercontent.com/4947697/104584226-ebf29d80-566a-11eb-8e1b-ea1750b17b39.png)

With the debugger I reached to line 122 where the exception is triggered:
`
html = markdown.markdown(text, extensions=EXTENSIONS)
`
The inputs are: text = "# 2 SRD002\nSome dummy text" and EXTENSIONS = ('markdown.extensions.extra', 'markdown.extensions.sane_lists', 'mdx_outline', 'mdx_math', <plantuml_markdown.PlantUMLMarkdownExtension>).
And indeed the resulted exception is e = ("module 'markdown' has no attribute '__ version_info __'").
![image](https://user-images.githubusercontent.com/4947697/104585352-8bfcf680-566c-11eb-99a3-836c94bb4e3f.png)

Checking that version info in a separate command prompt shows that indeed no '__ version_info __' exists for markdown:
![image](https://user-images.githubusercontent.com/4947697/104585604-ef872400-566c-11eb-92fa-92ea10a30f6e.png)
Strange that there is a ''version_info'' instead. I didn't play with python till now so have no clue from where this error comes, but will come back as soon find something else...

**Comment by sevendays** [comment]
The attribute is indeed missing (cfr. https://github.com/Python-Markdown/markdown/pull/709 ), but I don't exactly know which module attempts to read it (my guess is **plantuml-markdown**, I have ver. **3.2.2**)

I got two suggestions:

1) you should attempt to render the Markdown with atom/VScode using the https://atom.io/packages/markdown-preview-enhanced plugin rather than through PlantUML. The latter will just parse the markdown and discard everything outside the `@plantuml` tags

2) Setting the loggers to DEBUG may reveal the culprit (lines 34-36), though I believe it will be markdown-related rather than doorstop-related.
```
logging.basicConfig(stream=sys.stdout, level=logging.DEBUG)
logging.getLogger('doorstop').setLevel(logging.DEBUG)
logging.getLogger('MARKDOWN').setLevel(logging.DEBUG)
```
3) if the culprit is actually plantuml-markdown, which version do you have?

**Comment by DaPa** [comment]
I got it working, had to patch the markdown module:
![image](https://user-images.githubusercontent.com/4947697/104588432-04fe4d00-5671-11eb-897a-c1e0ff6e2674.png)
Will come with details in 1h.

**Comment by DaPa** [comment]
I have Markdown 2.6.11 (I think it's installed when installing Doorstop and might be that the Doorstop is the one asking for that old version - see above comment https://github.com/sevendays/doorhole/issues/2#issuecomment-759606327 where I forced to latest Markdown-3.3.3 but then hit another error: 'xml.etree.ElementTree.Element' object has no attribute 'getchildren' - all these happened when had Python 3.9).
Later I uninstalled 3.9  and installed Python 3.8, then installed Doorstop (via pip) and I got again the old Markdown 2.6.11 which complained as usual about __ version_info __:
![image](https://user-images.githubusercontent.com/4947697/104594840-64148f80-567a-11eb-981e-19b465725301.png)

Anyway this is what I had to change in my D:\tools\python\38\Lib\site-packages\markdown\ installation:

1. in __version__.py added one line after line 8:
```
version_info = (2, 6, 11, 'final', 0) 
__version_info__ = version_info        #        I added this line
```
2. in __init__.py added __ version_info __ at the line 35
```
from .__version__ import version, version_info, __version_info__  # noqa        #        here I added the last variable
```
3. then went into D:\tools\python\38\Lib\site-packages\markdown\\__ pycache__\ and deleted all content
4. then came back to D:\tools\python\38\Lib\site-packages\markdown\ and run __ main__.py which regenerated the __ pycache__
After these the Doorhole works fine! I know that this looks like a hack, but have no clue how to fix other way.
I'll close the issue, as anyway it's not due Doorhole... Thank you again for this nice tool!

**Comment by sevendays** [comment]
@DaPa I believe the fault is within **plantuml-markdown** https://github.com/mikitex70/plantuml-markdown because that's the one reading `version_info` / `__version_info__` from Markdown (which apparently switched from `version_info` to `__version_info__`).

Here's the specific line:

https://github.com/mikitex70/plantuml-markdown/blob/0a755808bba40e0f588df4063429663f35e424e8/plantuml_markdown.py#L309

```
        if markdown.__version_info__[0] < 3:
            md.preprocessors.add('plantuml', blockprocessor, '_begin')
        else:
            md.preprocessors.register(blockprocessor, 'plantuml', int(blockprocessor.config['priority']))
```

Here's what I have (I MAY have edited it - honestly I cannot remember) inside `%userprofile%AppData\Local\Programs\Python\Python38\Lib\site-packages\plantuml_markdown.py`:

```
        if markdown.version_info[0] < 3:
            md.preprocessors.add('plantuml', blockprocessor, '_begin')
        else:
            md.preprocessors.register(blockprocessor, 'plantuml', int(blockprocessor.config['priority']))
```

It could be a problem of installing the right version of plantuml-markdown, according to the specific version of markdown required by doorstop.

**Comment by DaPa** [comment]
Yes sir, thank you sir!
I reverted the markdown hacks and changed plantuml_markdown.py as you suggested and it works!  :-)

```
        #if markdown.__version_info__[0] < 3:
        if markdown.version_info[0] < 3:        #        DAPA: see https://github.com/sevendays/doorhole/issues/2#issuecomment-760204203
            md.preprocessors.add('plantuml', blockprocessor, '_begin')
        else:
            md.preprocessors.register(blockprocessor, 'plantuml', int(blockprocessor.config['priority']))
```

**Comment by sevendays** [comment]
Since I don't (yet) know how to manage dependencies I updated the README with the `pip` commands.

In your case removing `plantuml-markdown` and installing version 3.2.2 should solve the issue without hacks :)

**Comment by DaPa** [comment]
I think plantuml-markdown can be let to go to the latest (3.4.2) as latest doorstop 2.1.4 did upgrade the markdown module to 3.3.3.
So now for me doorhole works fine with latest plantuml-markdown:
![image](https://user-images.githubusercontent.com/4947697/104722517-9be10d00-5736-11eb-8234-e142dd3a9c94.png)
