### ISSUE TITLE
An error occured while displaying the content: Failed to run plantuml

### ISSUE THREAD

**Issue by MartyLake** [sevendays/doorhole#7]
Dear sevendays,
Your tool looks great, I wonder if it can make me go back to requirements tracking !
I tried to run it over the doorstop repository, and TUT017 displays this error message:
> An error occured while displaying the content: Failed to run plantuml: [Errno 2] Aucun fichier ou dossier de ce type: 'plantuml'

(which translates to "no file or directory of type: plantuml")

However, I can run `plantuml` from bash and it just works so I wonder what could I do to diagnose it further.

Best,

**Comment by sevendays** [comment]
Hi MartyLake,

Thanks. I doubt the tool will get you back on requirements tracking (some features are indeed still missing), but at least I hope editing will be simpler.

Regarding the error message, it is originated from this try-catch where Markdown is converted to html (lines 124-135 of `doorhole.py`):

			# change work dir to where the reqs are stored, otherwise images will not be rendered
			cwd_bkp = os.getcwd()
			try:
				os.path.dirname(os.path.realpath(__file__))
				os.chdir(item_path) # necessary to solve linked items with relative paths (e.g. images)
				html = self.md.convert(text)
				self.doc.setHtml(html)
			except Exception as e:
				warning = '**An error occurred while displaying the content**\n\n: '+ str(e) + '\n\n'
				text = warning + text
				self.doc.setMarkdown(text)
			os.chdir(cwd_bkp)

It looks like a problem of plantuml not being available system-wide, or a problem with plantuml-markdown-extension.

You will easily get around it by using a plantuml webserver, replacing line 25 of `doorhole.py`:

		server='',#'http://www.plantuml.com/plantuml',

 with this one:

		server='http://www.plantuml.com/plantuml',

But there are some cases where the company policies or firewalls are very strict, so I prefer to default to the local plantuml.

- Could you please check whether you're running doorhole.py within a container?
- Could you please check whether `plantuml` is visible from the TUT017 requirement-file folder?
- Could you try the below example script to confirm that plantuml-markdown is working?

        import markdown
        from plantuml_markdown import PlantUMLMarkdownExtension
        import tempfile
        
        EXTENSIONS = (
	        'markdown.extensions.extra',
	        'markdown.extensions.sane_lists',
	        'mdx_math',
	        PlantUMLMarkdownExtension(
		        server='',#'http://www.plantuml.com/plantuml',
		        cachedir=tempfile.gettempdir(),
		        format='svg',
		        classes='class1,class2',
		        title='UML',
		        alt='UML Diagram',
	        ),
        )
        
        md = markdown.Markdown(extensions=EXTENSIONS)
        text = """
        ```plantuml
        @startuml
        A -> B
        @enduml
        ```
        """
        html = md.convert(text)
        print(html)

**Comment by MartyLake** [comment]
Dear sevendays,

> Could you please check whether you're running doorhole.py within a container?

I am not running from any container.

> Could you please check whether plantuml is visible from the TUT017 requirement-file folder?

It is visible when run from "cmd.exe" and "git-bash", tested by running `plantuml -version` on both terminals.

> Could you try the below example script to confirm that plantuml-markdown is working?

This snippet returns an html file. When viewed, one can see the inline image that represents the converted plant uml diagram.

**Comment by sevendays** [comment]
Hi @MartyLake,


My setup for PlantUML is this one:
- I got a `PLANTUML` environment variable pointing to `C:\<my_own_path>\plantuml.jar`
- I got also the `C:\<my_own_path>` dir inside PATH
- And inside `C:\<my_own_path>` I got the following batch file `plantuml.bat`:

```
@echo off
set mypath=%~dp0
setlocal
java -jar %mypath%\plantuml.jar -charset UTF-8 %*
```

I made a quick test without the try-catch that renders TUT017 and the requirements tree in a QTabWidget.

https://gist.github.com/sevendays/e63e893566cbaf281f5110085ba9c38f

The first tab uses the local PlantUML renderer, the second tab uses plantuml.com.

Could you try to run it from the doorstop folder, please? I hope that any error would be apparent this way.

**Comment by sevendays** [comment]
Hi @MartyLake ,

With my last commit I enabled the plantuml webserver by default. This issue should be solved by this.
Feel free to reopen if you continue to experience problems.
