### ISSUE TITLE
mdx_math fails due to deprecation

### ISSUE THREAD

**Issue by neerdoc** [sevendays/doorhole#8]
Fresh install of doorhole according to instruction fails. Seems that the *mdx_math* Markdown extensions uses a deprecated version of _etree_. Latest update to *mdx_math* seems to be 2017, so perhaps changing to a different math extension is possible?

I have tested on python3.7, python3.8, python3.9 and python3.10 and it is broken in all of them.

**Comment by sevendays** [comment]
Hey @neerdoc ,

I gave a look at doorstop's source to find how they solved the issue in the first place. It looks like this:

https://github.com/doorstop-dev/doorstop/blob/dcc67c06dc4649ee84e6a239e7236e020e7ed154/doorstop/core/publisher.py#L26

    EXTENSIONS = (
      "markdown.extensions.extra",
      "markdown.extensions.sane_lists",
      PlantUMLMarkdownExtension(
        server="http://www.plantuml.com/plantuml",
        cachedir=tempfile.gettempdir(),
        format="svg",
        classes="class1,class2",
        title="UML",
        alt="UML Diagram",
        ),
    )

It looks like we should remove mdx_math entirely. But I'd like this tool to render math equations. Any suggestions?

PS: kudos for the latex export!

**Comment by sevendays** [comment]
There may be a package providing updated mdx_math: https://github.com/mitya57/python-markdown-math

**Comment by neerdoc** [comment]
Ah, just tried removing it and then doorhole works fine. The only difference is that any LaTeX-math equations are not typeset then in the editor.

I do not understand how to enable the updated package. It says its name is 'mdx_math', but I have installed it and keeping the name in doorhole.py does not load it if I remove the old version.

PS: Thanks!

**Comment by sevendays** [comment]
I didn't find a suitable workaround. When I realized I was pulling in too many dependencies only to replicate the mdx-math behaviour, I gave up and just removed the plugin.
